### ISSUE TITLE
CE Card Group

### ISSUE THREAD

**Issue by Hobokens** [TYPO3-Initiatives/content-blocks-examples#2]
When I try to open a card directly in backend instead of opening the module first I get the following error:

Core: Error handler (BE): PHP Warning: Undefined array key "example_card_group_card_group_item" in /www/htdocs/w01dd3f1/my-domain.de/typo3_src-12.4.6/typo3/sysext/backend/Classes/Controller/EditDocumentController.php line 2171

Edit form could not be loaded
The edit form could not be loaded for the requested records. This might be due to insufficient permissions.

**Comment by nhovratov** [comment]
Thanks, it's fixed!
