### ISSUE TITLE
Part of the backend module title without language file replacement

### ISSUE THREAD

**Issue by Hobokens** [TYPO3-Initiatives/content-blocks-examples#4]
When I open i.e. the accordion backend module I get the title

Edit example_accordion_accordion_item "#1" on page "Dev"

I tried without success in the language file

```
<trans-unit id="example.example_pinboard_pinboard_item" xml:space="preserve">
<source>Accordion</source>
</trans-unit>
```

and

```
<trans-unit id="example_pinboard_pinboard_item" xml:space="preserve">
<source>Accordion</source>
</trans-unit>
```

**Comment by nhovratov** [comment]
Fixed here: https://github.com/nhovratov/content-blocks/commit/3db4aefd688ecfc704dbaeeb64af1102503b26e5
